# Exploration

This Notebook is aimed at helping you apply in a structured way what you've learned about programming and working with data using pandas to explore the challenge dataset and contextualize the information we have with the business objective.

It's important to do so in a structured, organized way. Documenting your work properly and making it readable is essential to clearly communicate your results and keep track of all tasks you've done. 

## Import the dataset

Data files will be provided as "csv" files, which can be imported in pandas given the filepath to the pd.read_csv(FILE_PATH) function.

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd


df = pd.read_csv("/content/drive/MyDrive/Zambrano.csv")
print(df.head())

                      sucursal operating_date day_name  \
0  Panem - Hospital Zambrano N     2026-02-05   jueves
1  Panem - Hospital Zambrano N     2026-02-05   jueves
2  Panem - Hospital Zambrano N     2026-02-05   jueves
3  Panem - Hospital Zambrano N     2026-02-05   jueves
4  Panem - Hospital Zambrano N     2026-02-05   jueves

                 closing_time               captured_time  week_number  \
0  2026-02-05 08:09:04.327000  2026-02-05 08:05:09.710000            6
1  2026-02-05 08:09:04.327000  2026-02-05 08:05:18.727000            6
2  2026-02-05 08:09:04.327000  2026-02-05 08:05:40.727000            6
3  2026-02-05 08:09:04.327000  2026-02-05 08:05:41.490000            6
4  2026-02-05 08:09:04.327000  2026-02-05 08:05:42.210000            6

   pdv_txn_id  order_id   order_type order_subtype  ...  total_item  \
0      179310         1  Para llevar            '-  ...        55.0
1      179310         1  Para llevar            '-  ...       155.0
2      179310         1  Para llevar            '-  ...        55.0
3      179310         1  Para llevar            '-  ...         0.0
4      179310         1  Para llevar            '-  ...        55.0

   subtotal_cortesia_cancel iva_cortesia_cancel ieps_cortesia_cancel  \
0                       NaN                 NaN                  NaN
1                       NaN                 NaN                  NaN
2                       NaN                 NaN                  NaN
3                       NaN                 NaN                  NaN
4                       NaN                 NaN                  NaN

  total_cortesia_cancel subtotal_anulacion iva_anulacion ieps_anulacion  \
0                   NaN                NaN           NaN            NaN
1                   NaN                NaN           NaN            NaN
2                   NaN                NaN           NaN            NaN
3                   NaN                NaN           NaN            NaN
4                   NaN                NaN           NaN            NaN

  total_anulacion clave_platillo
0             NaN         JBF008
1             NaN          DE009
2             NaN         CBC001
3             NaN          MB002
4             NaN         CBC001

[5 rows x 46 columns]

To visualize what columns are present, we can use the .columns attribute

In [4]:
df.columns

Index(['sucursal', 'operating_date', 'day_name', 'closing_time',
       'captured_time', 'week_number', 'pdv_txn_id', 'order_id', 'order_type',
       'order_subtype', 'table_number', 'party_size', 'server', 'terminal',
       'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group',
       'description', 'is_modifier', 'quantity', 'unit_price',
       'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal',
       'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket',
       'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item',
       'subtotal_cortesia_cancel', 'iva_cortesia_cancel',
       'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion',
       'iva_anulacion', 'ieps_anulacion', 'total_anulacion', 'clave_platillo'],
      dtype='object')

## Data Description

Briefly describe:
* What the dataset contains (in your own words)
# Contains information about the sales that the zambrano branch made. 
* How many rows and columns it has
# 4268 , 46

In [5]:
# Display basic dataset information
print("Dataset Shape (rows, columns):", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nColumn names:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nBasic statistics:")
print(df.describe())

Dataset Shape (rows, columns): (4268, 46)

First few rows:
                      sucursal operating_date day_name  \
0  Panem - Hospital Zambrano N     2026-02-05   jueves
1  Panem - Hospital Zambrano N     2026-02-05   jueves
2  Panem - Hospital Zambrano N     2026-02-05   jueves
3  Panem - Hospital Zambrano N     2026-02-05   jueves
4  Panem - Hospital Zambrano N     2026-02-05   jueves

                 closing_time               captured_time  week_number  \
0  2026-02-05 08:09:04.327000  2026-02-05 08:05:09.710000            6
1  2026-02-05 08:09:04.327000  2026-02-05 08:05:18.727000            6
2  2026-02-05 08:09:04.327000  2026-02-05 08:05:40.727000            6
3  2026-02-05 08:09:04.327000  2026-02-05 08:05:41.490000            6
4  2026-02-05 08:09:04.327000  2026-02-05 08:05:42.210000            6

   pdv_txn_id  order_id   order_type order_subtype  ...  total_item  \
0      179310         1  Para llevar            '-  ...        55.0
1      179310         1  Para llevar            '-  ...       155.0
2      179310         1  Para llevar            '-  ...        55.0
3      179310         1  Para llevar            '-  ...         0.0
4      179310         1  Para llevar            '-  ...        55.0

   subtotal_cortesia_cancel iva_cortesia_cancel ieps_cortesia_cancel  \
0                       NaN                 NaN                  NaN
1                       NaN                 NaN                  NaN
2                       NaN                 NaN                  NaN
3                       NaN                 NaN                  NaN
4                       NaN                 NaN                  NaN

  total_cortesia_cancel subtotal_anulacion iva_anulacion ieps_anulacion  \
0                   NaN                NaN           NaN            NaN
1                   NaN                NaN           NaN            NaN
2                   NaN                NaN           NaN            NaN
3                   NaN                NaN           NaN            NaN
4                   NaN                NaN           NaN            NaN

  total_anulacion clave_platillo
0             NaN         JBF008
1             NaN          DE009
2             NaN         CBC001
3             NaN          MB002
4             NaN         CBC001

[5 rows x 46 columns]

Column names:
['sucursal', 'operating_date', 'day_name', 'closing_time', 'captured_time', 'week_number', 'pdv_txn_id', 'order_id', 'order_type', 'order_subtype', 'table_number', 'party_size', 'server', 'terminal', 'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group', 'description', 'is_modifier', 'quantity', 'unit_price', 'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal', 'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket', 'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item', 'subtotal_cortesia_cancel', 'iva_cortesia_cancel', 'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion', 'iva_anulacion', 'ieps_anulacion', 'total_anulacion', 'clave_platillo']

Data types:
sucursal                     object
operating_date               object
day_name                     object
closing_time                 object
captured_time                object
week_number                   int64
pdv_txn_id                    int64
order_id                      int64
order_type                   object
order_subtype                object
table_number                float64
party_size                    int64
server                       object
terminal                     object
capture_terminal             object
action                       object
item                         object
modifier                     object
group_type                   object
group                        object
description                  object
is_modifier                  object
quantity                    float64
unit_price                  float64
unit_price_with_mods        float64
cost_actual                 float64
cost_with_mods              float64
cost_ideal                  float64
discount                    float64
subtotal_ticket             float64
iva_ticket                  float64
ieps_ticket                 float64
total_ticket                float64
subtotal_item               float64
iva_item                    float64
ieps_item                   float64
total_item                  float64
subtotal_cortesia_cancel    float64
iva_cortesia_cancel         float64
ieps_cortesia_cancel        float64
total_cortesia_cancel       float64
subtotal_anulacion          float64
iva_anulacion               float64
ieps_anulacion              float64
total_anulacion             float64
clave_platillo               object
dtype: object

Basic statistics:
       week_number     pdv_txn_id     order_id  table_number   party_size  \
count  4268.000000    4268.000000  4268.000000    772.000000  4268.000000
mean      6.554124  179934.435333    80.883786     17.563472     1.062793
std       0.497120     363.287666    48.458706      9.099671     0.322273
min       6.000000  179310.000000     1.000000      1.000000     1.000000
25%       6.000000  179620.750000    40.000000      9.000000     1.000000
50%       7.000000  179923.000000    78.000000     14.000000     1.000000
75%       7.000000  180261.000000   121.000000     27.000000     1.000000
max       7.000000  180563.000000   198.000000     29.000000     5.000000

          quantity   unit_price  unit_price_with_mods  cost_actual  \
count  4268.000000  4265.000000           4265.000000  4265.000000
mean      1.029522    59.591887             59.591887    10.375151
std       0.326288    58.320678             60.651253    23.119546
min       1.000000     0.000000              0.000000     0.000000
25%       1.000000     0.000000              0.000000     0.000000
50%       1.000000    45.000000             45.000000     1.517000
75%       1.000000    85.000000             87.000000    12.224000
max      10.000000   215.000000            236.000000   477.959600

       cost_with_mods  ...    ieps_item   total_item  \
count     4265.000000  ...  4251.000000  4251.000000
mean        10.375151  ...     0.973095    61.211416
std         23.119553  ...     2.002214    60.462957
min          0.000000  ...     0.000000     0.000000
25%          0.000000  ...     0.000000     0.000000
50%          1.517000  ...     0.000000    45.000000
75%         12.224000  ...     0.000000    90.000000
max        477.959600  ...    13.333300   310.000000

       subtotal_cortesia_cancel  iva_cortesia_cancel  ieps_cortesia_cancel  \
count                  3.000000                  3.0                   3.0
mean                  96.293333                  0.0                   0.0
std                  125.094483                  0.0                   0.0
min                   24.070000                  0.0                   0.0
25%                   24.070000                  0.0                   0.0
50%                   24.070000                  0.0                   0.0
75%                  132.405000                  0.0                   0.0
max                  240.740000                  0.0                   0.0

       total_cortesia_cancel  subtotal_anulacion  iva_anulacion  \
count               3.000000           17.000000      17.000000
mean              104.000000           57.187665       6.239353
std               135.099963           50.017650       8.451947
min                26.000000            0.000000       0.000000
25%                26.000000            8.620700       0.000000
50%                26.000000           60.185200       1.379300
75%               143.000000           95.689700      15.034500
max               260.000000          168.103400      26.896600

       ieps_anulacion  total_anulacion
count       17.000000        17.000000
mean         1.119824        64.882353
std          2.585552        57.339867
min          0.000000         0.000000
25%          0.000000        10.000000
50%          0.000000        65.000000
75%          0.000000       111.000000
max          8.518500       195.000000

[8 rows x 28 columns]

## Details

Answer the following questions:

1. What does one single row represent?
# a single item within a restaurant order/transaction
2. What does each column represent? 
    Which columns are categorical, numerical, datetime, or ID (identifier)? 
# Categorical: 'sucursal', 'day_name', 'order_type', 'order_subtype', 'server', 'terminal', 'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group', 'description', 'is_modifier', 'clave_platillo'

# Numerical: ['week_number', 'pdv_txn_id', 'order_id', 'party_size', 'table_number', 'quantity', 'unit_price', 'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal', 'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket', 'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item', 'subtotal_cortesia_cancel', 'iva_cortesia_cancel', 'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion', 'iva_anulacion', 'ieps_anulacion', 'total_anulacion']

# Datetime: operating_date, closing_time, captured_time

# ID: pdv_txn_id, order_id, clave_platillo

In [6]:
df.head()

,sucursal,operating_date,day_name,closing_time,captured_time,week_number,pdv_txn_id,order_id,order_type,order_subtype,...,total_item,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion,clave_platillo
0,Panem - Hospital Zambrano N,2026-02-05,jueves,2026-02-05 08:09:04.327000,2026-02-05 08:05:09.710000,6,179310,1,Para llevar,'-,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JBF008
1,Panem - Hospital Zambrano N,2026-02-05,jueves,2026-02-05 08:09:04.327000,2026-02-05 08:05:18.727000,6,179310,1,Para llevar,'-,...,155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE009
2,Panem - Hospital Zambrano N,2026-02-05,jueves,2026-02-05 08:09:04.327000,2026-02-05 08:05:40.727000,6,179310,1,Para llevar,'-,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC001
3,Panem - Hospital Zambrano N,2026-02-05,jueves,2026-02-05 08:09:04.327000,2026-02-05 08:05:41.490000,6,179310,1,Para llevar,'-,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MB002
4,Panem - Hospital Zambrano N,2026-02-05,jueves,2026-02-05 08:09:04.327000,2026-02-05 08:05:42.210000,6,179310,1,Para llevar,'-,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC001

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4268 entries, 0 to 4267
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   sucursal                  4268 non-null   object
 1   operating_date            4268 non-null   object
 2   day_name                  4268 non-null   object
 3   closing_time              4268 non-null   object
 4   captured_time             4268 non-null   object
 5   week_number               4268 non-null   int64
 6   pdv_txn_id                4268 non-null   int64
 7   order_id                  4268 non-null   int64
 8   order_type                4268 non-null   object
 9   order_subtype             4268 non-null   object
 10  table_number              772 non-null    float64
 11  party_size                4268 non-null   int64
 12  server                    4268 non-null   object
 13  terminal                  4268 non-null   object
 14  capture_terminal          4265 non-null   object
 15  action                    4268 non-null   object
 16  item                      4268 non-null   object
 17  modifier                  1218 non-null   object
 18  group_type                4268 non-null   object
 19  group                     4268 non-null   object
 20  description               4268 non-null   object
 21  is_modifier               4265 non-null   object
 22  quantity                  4268 non-null   float64
 23  unit_price                4265 non-null   float64
 24  unit_price_with_mods      4265 non-null   float64
 25  cost_actual               4265 non-null   float64
 26  cost_with_mods            4265 non-null   float64
 27  cost_ideal                4265 non-null   float64
 28  discount                  4265 non-null   float64
 29  subtotal_ticket           4265 non-null   float64
 30  iva_ticket                4265 non-null   float64
 31  ieps_ticket               4265 non-null   float64
 32  total_ticket              4265 non-null   float64
 33  subtotal_item             4251 non-null   float64
 34  iva_item                  4251 non-null   float64
 35  ieps_item                 4251 non-null   float64
 36  total_item                4251 non-null   float64
 37  subtotal_cortesia_cancel  3 non-null      float64
 38  iva_cortesia_cancel       3 non-null      float64
 39  ieps_cortesia_cancel      3 non-null      float64
 40  total_cortesia_cancel     3 non-null      float64
 41  subtotal_anulacion        17 non-null     float64
 42  iva_anulacion             17 non-null     float64
 43  ieps_anulacion            17 non-null     float64
 44  total_anulacion           17 non-null     float64
 45  clave_platillo            4268 non-null   object
dtypes: float64(24), int64(4), object(18)
memory usage: 1.5+ MB

In [8]:
df.describe()

,week_number,pdv_txn_id,order_id,table_number,party_size,quantity,unit_price,unit_price_with_mods,cost_actual,cost_with_mods,...,ieps_item,total_item,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion
count,4268.000000,4268.000000,4268.000000,772.000000,4268.000000,4268.000000,4265.000000,4265.000000,4265.000000,4265.000000,...,4251.000000,4251.000000,3.000000,3.0,3.0,3.000000,17.000000,17.000000,17.000000,17.000000
mean,6.554124,179934.435333,80.883786,17.563472,1.062793,1.029522,59.591887,59.591887,10.375151,10.375151,...,0.973095,61.211416,96.293333,0.0,0.0,104.000000,57.187665,6.239353,1.119824,64.882353
std,0.497120,363.287666,48.458706,9.099671,0.322273,0.326288,58.320678,60.651253,23.119546,23.119553,...,2.002214,60.462957,125.094483,0.0,0.0,135.099963,50.017650,8.451947,2.585552,57.339867
min,6.000000,179310.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,24.070000,0.0,0.0,26.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,179620.750000,40.000000,9.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,24.070000,0.0,0.0,26.000000,8.620700,0.000000,0.000000,10.000000
50%,7.000000,179923.000000,78.000000,14.000000,1.000000,1.000000,45.000000,45.000000,1.517000,1.517000,...,0.000000,45.000000,24.070000,0.0,0.0,26.000000,60.185200,1.379300,0.000000,65.000000
75%,7.000000,180261.000000,121.000000,27.000000,1.000000,1.000000,85.000000,87.000000,12.224000,12.224000,...,0.000000,90.000000,132.405000,0.0,0.0,143.000000,95.689700,15.034500,0.000000,111.000000
max,7.000000,180563.000000,198.000000,29.000000,5.000000,10.000000,215.000000,236.000000,477.959600,477.959600,...,13.333300,310.000000,240.740000,0.0,0.0,260.000000,168.103400,26.896600,8.518500,195.000000

In [17]:
categorical = df.select_dtypes(include="object").columns
integer = df.select_dtypes(include="int64").columns
float = df.select_dtypes(include="float64").columns

print("Categorical:", list(categorical))
print("Integer:", list(integer))
print("Float:", list(float))
print("Numerical:", list(integer) + list(float))

Categorical: ['sucursal', 'day_name', 'order_type', 'order_subtype', 'server', 'terminal', 'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group', 'description', 'is_modifier', 'clave_platillo']
Integer: ['week_number', 'pdv_txn_id', 'order_id', 'party_size']
Float: ['table_number', 'quantity', 'unit_price', 'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal', 'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket', 'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item', 'subtotal_cortesia_cancel', 'iva_cortesia_cancel', 'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion', 'iva_anulacion', 'ieps_anulacion', 'total_anulacion']
Numerical: ['week_number', 'pdv_txn_id', 'order_id', 'party_size', 'table_number', 'quantity', 'unit_price', 'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal', 'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket', 'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item', 'subtotal_cortesia_cancel', 'iva_cortesia_cancel', 'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion', 'iva_anulacion', 'ieps_anulacion', 'total_anulacion']

In [14]:
df["operating_date"] = pd.to_datetime(df["operating_date"], errors="coerce")
df["closing_time"]   = pd.to_datetime(df["closing_time"], errors="coerce")
df["captured_time"]  = pd.to_datetime(df["captured_time"], errors="coerce")

df[["operating_date", "closing_time", "captured_time"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4268 entries, 0 to 4267
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   operating_date  4268 non-null   datetime64[ns]
 1   closing_time    4250 non-null   datetime64[ns]
 2   captured_time   4258 non-null   datetime64[ns]
dtypes: datetime64[ns](3)
memory usage: 100.2 KB

In [16]:
id_columns = ["pdv_txn_id", "order_id", "clave_platillo"]
print("ID:", id_columns)

ID: ['pdv_txn_id', 'order_id', 'clave_platillo']

## Data Types and Conversions

Answer: 
1. Which columns are:
    Categorical
    Numerical
    Datetime
    ID (identifier)

Ensure that the columns are in the proper data type for their use, and convert them in case they aren't. Include text and code, showing your process and the final result of your work.

In [18]:

# --- Identify column types ---
categorical_cols = df.select_dtypes(include="object").columns.tolist()
numerical_cols   = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
datetime_cols    = df.select_dtypes(include="datetime64[ns]").columns.tolist()

# --- Manually define ID columns ---
id_cols = ["pdv_txn_id", "order_id", "clave_platillo"]

print("Categorical:", categorical_cols)
print("Numerical:", numerical_cols)
print("Datetime:", datetime_cols)
print("ID:", id_cols)

Categorical: ['sucursal', 'day_name', 'order_type', 'order_subtype', 'server', 'terminal', 'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group', 'description', 'is_modifier', 'clave_platillo']
Numerical: ['week_number', 'pdv_txn_id', 'order_id', 'table_number', 'party_size', 'quantity', 'unit_price', 'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal', 'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket', 'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item', 'subtotal_cortesia_cancel', 'iva_cortesia_cancel', 'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion', 'iva_anulacion', 'ieps_anulacion', 'total_anulacion']
Datetime: ['operating_date', 'closing_time', 'captured_time']
ID: ['pdv_txn_id', 'order_id', 'clave_platillo']

## Data Quality and Errors 

Analyze:
1. Does the data contain missing values?
2. Are there duplicated rows?

In [19]:
# 1. Check for missing values
missing_values = df.isna().sum()
total_missing = missing_values.sum()

print("Missing values per column:\n")
print(missing_values)

print("\nTotal missing values in dataset:", total_missing)

# 2. Check for duplicated rows

duplicate_rows = df.duplicated().sum()

print("\nNumber of duplicated rows:", duplicate_rows)

Missing values per column:

sucursal                       0
operating_date                 0
day_name                       0
closing_time                  18
captured_time                 10
week_number                    0
pdv_txn_id                     0
order_id                       0
order_type                     0
order_subtype                  0
table_number                3496
party_size                     0
server                         0
terminal                       0
capture_terminal               3
action                         0
item                           0
modifier                    3050
group_type                     0
group                          0
description                    0
is_modifier                    3
quantity                       0
unit_price                     3
unit_price_with_mods           3
cost_actual                    3
cost_with_mods                 3
cost_ideal                     3
discount                       3
subtotal_ticket                3
iva_ticket                     3
ieps_ticket                    3
total_ticket                   3
subtotal_item                 17
iva_item                      17
ieps_item                     17
total_item                    17
subtotal_cortesia_cancel    4265
iva_cortesia_cancel         4265
ieps_cortesia_cancel        4265
total_cortesia_cancel       4265
subtotal_anulacion          4251
iva_anulacion               4251
ieps_anulacion              4251
total_anulacion             4251
clave_platillo                 0
dtype: int64

Total missing values in dataset: 40742

Number of duplicated rows: 0

## Exploration

Use different exploration methods such as .describe() (check the class activities and presentations) to inspect patterns in the data, and to spot potential inconsistencies. 

Look for values that don't make sense in a real-world context.

## Prediction Shaping

When it comes to prediction, we are tryong to guess an unknown number using past examples. Each example must have the same format as what we want to predict in the future. 

For example:
* Using a house's number of rooms, total square footage, number of bedrooms and location to predict its price
* Predicting a plant's growth based on the amount of sunlight, water, and nutrients in the soil 

So before thinking about Machine Learning and AI, we need to answer: What does one thing we want to predict look like? What information would we use to predict what we want to predict, and what should that look like? 

Our training data should look just like our prediction data, except we already know the answer (the target variable's real value). For example, in the house price example, the question should be "how much did this house with 4 bedrooms, located in X neighborhood, with Y square footage sell for?" Your dataset should be able to answer that in a single row. 


Answer the questions:
1. What do we want to predict? 
# The total sales value of an item or transaction for example, the column total_item or subtotal_ticket
2. What would a single row for prediction look like? 
3. What do we need to do to the dataset to achieve this?

In [ ]:
# 2.
df.iloc[0]
# One sold item within a restaurant transaction, with all its contextual and numerical attributes used to estimate the final sale amount.

sucursal                    Panem - Hospital Zambrano N
operating_date                      2026-02-05 00:00:00
day_name                                         jueves
closing_time                 2026-02-05 08:09:04.327000
captured_time                2026-02-05 08:05:09.710000
week_number                                           6
pdv_txn_id                                       179310
order_id                                              1
order_type                                  Para llevar
order_subtype                                        '-
table_number                                        NaN
party_size                                            1
server                                         Zambrano
terminal                                        SERVER1
capture_terminal                                SERVER1
action                                            Venta
item                                         JUGO VERDE
modifier                                            NaN
group_type                                    Alimentos
group                             JUGOS Y BEBIDAS FRIAS
description                                  JUGO VERDE
is_modifier                                       False
quantity                                            1.0
unit_price                                         55.0
unit_price_with_mods                               55.0
cost_actual                                        29.0
cost_with_mods                                     29.0
cost_ideal                                         26.0
discount                                            0.0
subtotal_ticket                                  331.42
iva_ticket                                        44.14
ieps_ticket                                        4.44
total_ticket                                      380.0
subtotal_item                                   47.4138
iva_item                                         7.5862
ieps_item                                           0.0
total_item                                         55.0
subtotal_cortesia_cancel                            NaN
iva_cortesia_cancel                                 NaN
ieps_cortesia_cancel                                NaN
total_cortesia_cancel                               NaN
subtotal_anulacion                                  NaN
iva_anulacion                                       NaN
ieps_anulacion                                      NaN
total_anulacion                                     NaN
clave_platillo                                   JBF008
Name: 0, dtype: object

In [ ]:
#3

##a) Handle missing values

df = df.dropna()
## b) Convert categorical variables to numerical encoding

df_encoded = pd.get_dummies(df, drop_first=True)

##Remove identifier columns (not useful for prediction)
df_encoded = df_encoded.drop(columns=["pdv_txn_id", "order_id", "clave_platillo"], errors="ignore")

## Open questions

Surely, you'll have a lot of questions about the dataset. Whenever you're exploring, it's a good idea to keep a log of unanswered questions, so that when you meet with the training partner again, you can make good use of their time with you. 

What questions do you have about the dataset that you can't yet answer? 
What information would you ask the company to better understand the dataset? 
Given the information in the dataset, what do you consider worth exploring in the later weeks?